package Vista;

/**
 *
 * @author edu
 */
public class HistorialMascota extends javax.swing.JFrame {

    /**
     * Creates new form HistorialMascota
     */
    public HistorialMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Ver_detalle = new javax.swing.JMenuItem();
        Ver_detalle_receta = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clave_mascota = new jtextfieldround.JTextFieldRound();
        Bot_buscar_paciente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Tipo_historial = new javax.swing.JComboBox<>();
        Raza_Mascota = new javax.swing.JLabel();
        Nombre_Mascota = new javax.swing.JLabel();
        Cedula_Pro = new javax.swing.JLabel();
        Sexo_Mascota = new javax.swing.JLabel();
        Edad_Mascota = new javax.swing.JLabel();
        Peso_Mascota = new javax.swing.JLabel();
        Especie_Mascota = new javax.swing.JLabel();
        nombres_Pro = new javax.swing.JLabel();
        Telf_Pro2 = new javax.swing.JLabel();
        corre_Pro3 = new javax.swing.JLabel();
        Direc_Pro = new javax.swing.JLabel();
        Id_mascota = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Bot_limpiar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        Boton_regresar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Bot_limpiar2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ocultar_tablas = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tablas_Historial = new rojeru_san.complementos.RSTableMetro();

        Ver_detalle.setText("Ver Detalladamente");
        jPopupMenu1.add(Ver_detalle);

        Ver_detalle_receta.setText("Ver Detalle Receta");
        jPopupMenu1.add(Ver_detalle_receta);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 252, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(246, 252, 254));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(18, 125, 161));
        jLabel1.setText("HISTORIAL CLINICO");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 280, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 40));

        clave_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clave_mascotaActionPerformed(evt);
            }
        });
        jPanel1.add(clave_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 30));

        Bot_buscar_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_30px_1.png"))); // NOI18N
        Bot_buscar_paciente.setBorder(null);
        Bot_buscar_paciente.setBorderPainted(false);
        Bot_buscar_paciente.setContentAreaFilled(false);
        Bot_buscar_paciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_buscar_paciente.setFocusPainted(false);
        jPanel1.add(Bot_buscar_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 50, 30));

        jLabel12.setBackground(new java.awt.Color(0, 153, 153));
        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(18, 125, 161));
        jLabel12.setText("EDAD");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, 30));

        jLabel17.setBackground(new java.awt.Color(0, 153, 153));
        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(18, 125, 161));
        jLabel17.setText("PESO");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, 30));

        jLabel9.setBackground(new java.awt.Color(0, 153, 153));
        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 125, 161));
        jLabel9.setText("SEXO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 30));

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(18, 125, 161));
        jLabel10.setText("RAZA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 40, 30));

        jLabel13.setBackground(new java.awt.Color(0, 153, 153));
        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(18, 125, 161));
        jLabel13.setText("ESPECIE");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 60, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(18, 125, 161));
        jLabel14.setText("FICHA MASCOTA");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 85, -1, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(18, 125, 161));
        jLabel18.setText("CEDULA");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 125, 161));
        jLabel2.setText("NOMBRES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(18, 125, 161));
        jLabel19.setText("CORREO");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 125, 161));
        jLabel8.setText("DIRECCION");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(18, 125, 161));
        jLabel20.setText("TELEFONO");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 300, -1, -1));

        Tipo_historial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Examenes", "Recetas" }));
        jPanel1.add(Tipo_historial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 210, -1));

        Raza_Mascota.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Raza_Mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Raza_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 110, 20));

        Nombre_Mascota.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Nombre_Mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Nombre_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 100, 20));

        Cedula_Pro.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Cedula_Pro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Cedula_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 100, 20));

        Sexo_Mascota.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Sexo_Mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Sexo_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 80, 20));

        Edad_Mascota.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Edad_Mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Edad_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 50, 20));

        Peso_Mascota.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Peso_Mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Peso_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 80, 20));

        Especie_Mascota.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Especie_Mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Especie_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 110, 20));

        nombres_Pro.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        nombres_Pro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nombres_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 250, 20));

        Telf_Pro2.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Telf_Pro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Telf_Pro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 150, 20));

        corre_Pro3.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        corre_Pro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(corre_Pro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 180, 20));

        Direc_Pro.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        Direc_Pro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Direc_Pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 220, 20));

        Id_mascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Id_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, 30));

        jLabel7.setBackground(new java.awt.Color(0, 153, 153));
        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 125, 161));
        jLabel7.setText("NOMBRE");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, 30));

        jPanel2.setBackground(new java.awt.Color(23, 161, 207));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(103, 206, 233));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bot_limpiar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_broom_25px.png"))); // NOI18N
        Bot_limpiar1.setBorderPainted(false);
        Bot_limpiar1.setContentAreaFilled(false);
        Bot_limpiar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel4.add(Bot_limpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 50, 30));

        jLabel21.setBackground(new java.awt.Color(0, 153, 153));
        jLabel21.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("LIMPIAR");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 60, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1000, 30));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DATOS MASCOTA");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 20));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SALIR");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 50, 20));

        Boton_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        Boton_regresar.setBorder(null);
        Boton_regresar.setBorderPainted(false);
        Boton_regresar.setContentAreaFilled(false);
        Boton_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Boton_regresar.setFocusPainted(false);
        jPanel2.add(Boton_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 50, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1000, 50));

        jPanel5.setBackground(new java.awt.Color(23, 161, 207));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bot_limpiar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_broom_25px.png"))); // NOI18N
        Bot_limpiar2.setBorder(null);
        Bot_limpiar2.setBorderPainted(false);
        Bot_limpiar2.setContentAreaFilled(false);
        Bot_limpiar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_limpiar2.setFocusPainted(false);
        jPanel5.add(Bot_limpiar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 50, 30));

        jLabel22.setBackground(new java.awt.Color(0, 153, 153));
        jLabel22.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("LIMPIAR");
        jPanel5.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 60, 30));

        jPanel6.setBackground(new java.awt.Color(103, 206, 233));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(0, 153, 153));
        jLabel23.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("LIMPIAR");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 60, 30));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1000, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 1000, 30));

        jPanel7.setBackground(new java.awt.Color(23, 161, 207));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(103, 206, 233));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(0, 153, 153));
        jLabel24.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("LIMPIAR");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 60, 30));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 1000, 30));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("DATOS PROPIETARIO");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 20));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1000, 40));

        ocultar_tablas.setBackground(new java.awt.Color(246, 252, 254));
        ocultar_tablas.setAutoscrolls(false);
        ocultar_tablas.setBorder(null);
        jPanel1.add(ocultar_tablas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 980, 200));

        Tablas_Historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tablas_Historial.setAltoHead(25);
        Tablas_Historial.setAutoscrolls(false);
        Tablas_Historial.setColorBackgoundHead(new java.awt.Color(23, 161, 207));
        Tablas_Historial.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tablas_Historial.setColorBordeHead(new java.awt.Color(255, 255, 255));
        Tablas_Historial.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tablas_Historial.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Tablas_Historial.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Tablas_Historial.setColorSelBackgound(new java.awt.Color(153, 204, 255));
        Tablas_Historial.setColorSelForeground(new java.awt.Color(51, 51, 51));
        Tablas_Historial.setComponentPopupMenu(jPopupMenu1);
        Tablas_Historial.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tablas_Historial.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tablas_Historial.setFuenteHead(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        Tablas_Historial.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(Tablas_Historial);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 950, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clave_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clave_mascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clave_mascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialMascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bot_buscar_paciente;
    public javax.swing.JButton Bot_limpiar1;
    public javax.swing.JButton Bot_limpiar2;
    public javax.swing.JButton Boton_regresar;
    public javax.swing.JLabel Cedula_Pro;
    public javax.swing.JLabel Direc_Pro;
    public javax.swing.JLabel Edad_Mascota;
    public javax.swing.JLabel Especie_Mascota;
    public javax.swing.JLabel Id_mascota;
    public javax.swing.JLabel Nombre_Mascota;
    public javax.swing.JLabel Peso_Mascota;
    public javax.swing.JLabel Raza_Mascota;
    public javax.swing.JLabel Sexo_Mascota;
    public rojeru_san.complementos.RSTableMetro Tablas_Historial;
    public javax.swing.JLabel Telf_Pro2;
    public javax.swing.JComboBox<String> Tipo_historial;
    public javax.swing.JMenuItem Ver_detalle;
    public javax.swing.JMenuItem Ver_detalle_receta;
    public jtextfieldround.JTextFieldRound clave_mascota;
    public javax.swing.JLabel corre_Pro3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel nombres_Pro;
    public javax.swing.JTextField ocultar_tablas;
    // End of variables declaration//GEN-END:variables
}
