/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author PC
 */
public class HistorialEmpleadosActivos extends javax.swing.JFrame {

    /**
     * Creates new form HistorialEliminados
     */
    public HistorialEmpleadosActivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Restaurar = new javax.swing.JMenuItem();
        Restaurar1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new jtextfieldround.JTextFieldRound();
        jPanel3 = new javax.swing.JPanel();
        Bot_Regresar_Repo = new javax.swing.JButton();
        Generar_Rep_Mascota = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Bot_RepBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboFiltro = new javax.swing.JComboBox<>();
        CheckElimimados = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tablas_Historial = new rojeru_san.complementos.RSTableMetro();

        Restaurar.setText("Eliminar");
        jPopupMenu1.add(Restaurar);

        Restaurar1.setText("Restaurar");
        jPopupMenu1.add(Restaurar1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(246, 252, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(23, 161, 207));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HISTORIAL PERSONAL");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 50));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 260, 30));

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bot_Regresar_Repo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        Bot_Regresar_Repo.setToolTipText("salir");
        Bot_Regresar_Repo.setBorder(null);
        Bot_Regresar_Repo.setBorderPainted(false);
        Bot_Regresar_Repo.setContentAreaFilled(false);
        Bot_Regresar_Repo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Regresar_Repo.setFocusPainted(false);
        Bot_Regresar_Repo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_Regresar_RepoActionPerformed(evt);
            }
        });
        jPanel3.add(Bot_Regresar_Repo, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 40));

        Generar_Rep_Mascota.setBackground(new java.awt.Color(255, 255, 255));
        Generar_Rep_Mascota.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Generar_Rep_Mascota.setForeground(new java.awt.Color(18, 125, 161));
        Generar_Rep_Mascota.setText("Generar Reporte");
        Generar_Rep_Mascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Generar_Rep_Mascota.setFocusPainted(false);
        jPanel3.add(Generar_Rep_Mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 230, 30));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SALIR");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 60, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 1000, 50));

        Bot_RepBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_30px_1.png"))); // NOI18N
        Bot_RepBuscar.setToolTipText("buscar");
        Bot_RepBuscar.setBorder(null);
        Bot_RepBuscar.setBorderPainted(false);
        Bot_RepBuscar.setContentAreaFilled(false);
        Bot_RepBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_RepBuscar.setFocusPainted(false);
        Bot_RepBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_RepBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Bot_RepBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVeterinaria.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 170, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 125, 161));
        jLabel2.setText("Filtro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 50));

        comboFiltro.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        comboFiltro.setForeground(new java.awt.Color(51, 51, 51));
        comboFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Veterinarios", "Auxiliar", "Secretarias", "Propietarios", "Mascotas" }));
        comboFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(comboFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 270, 30));

        CheckElimimados.setBackground(new java.awt.Color(246, 252, 254));
        CheckElimimados.setFont(new java.awt.Font("Nirmala UI", 0, 13)); // NOI18N
        CheckElimimados.setForeground(new java.awt.Color(18, 125, 161));
        CheckElimimados.setText("Eliminados");
        CheckElimimados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CheckElimimados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckElimimadosActionPerformed(evt);
            }
        });
        jPanel1.add(CheckElimimados, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 150, -1, -1));

        Tablas_Historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tablas_Historial.setAltoHead(25);
        Tablas_Historial.setAutoscrolls(false);
        Tablas_Historial.setColorBackgoundHead(new java.awt.Color(23, 161, 207));
        Tablas_Historial.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tablas_Historial.setColorBordeHead(new java.awt.Color(255, 255, 255));
        Tablas_Historial.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tablas_Historial.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Tablas_Historial.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Tablas_Historial.setColorSelBackgound(new java.awt.Color(153, 204, 255));
        Tablas_Historial.setColorSelForeground(new java.awt.Color(51, 51, 51));
        Tablas_Historial.setComponentPopupMenu(jPopupMenu1);
        Tablas_Historial.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tablas_Historial.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tablas_Historial.setFuenteHead(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Tablas_Historial.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Tablas_Historial);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 180, 970, 330));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot_Regresar_RepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_Regresar_RepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bot_Regresar_RepoActionPerformed

    private void Bot_RepBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_RepBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bot_RepBuscarActionPerformed

    private void CheckElimimadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckElimimadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckElimimadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialEmpleadosActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialEmpleadosActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialEmpleadosActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialEmpleadosActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialEmpleadosActivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bot_Regresar_Repo;
    public javax.swing.JButton Bot_RepBuscar;
    public javax.swing.JCheckBox CheckElimimados;
    public javax.swing.JButton Generar_Rep_Mascota;
    public javax.swing.JMenuItem Restaurar;
    public javax.swing.JMenuItem Restaurar1;
    public rojeru_san.complementos.RSTableMetro Tablas_Historial;
    public javax.swing.JComboBox<String> comboFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    public jtextfieldround.JTextFieldRound txtBuscar;
    // End of variables declaration//GEN-END:variables
}
