/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class HorarioEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form HorarioEmpleados
     */
    public HorarioEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btSal = new javax.swing.JButton();
        Bot_Reporte = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JSeparator();
        Bot_Limpiar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        trId = new jtextfieldround.JTextFieldRound();
        trNom = new jtextfieldround.JTextFieldRound();
        jLabel15 = new javax.swing.JLabel();
        trApe = new jtextfieldround.JTextFieldRound();
        jSeparator5 = new javax.swing.JSeparator();
        btAgr = new javax.swing.JButton();
        btMod = new javax.swing.JButton();
        btEli = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        btMed = new javax.swing.JButton();
        trCod = new jtextfieldround.JTextFieldRound();
        trDia = new jtextfieldround.JTextFieldRound();
        trHI = new jtextfieldround.JTextFieldRound();
        trHF = new jtextfieldround.JTextFieldRound();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        trCo = new jtextfieldround.JTextFieldRound();
        btHor = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        id_servicio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 252, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, 30));

        btSal.setBackground(new java.awt.Color(0, 153, 153));
        btSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSal.setForeground(new java.awt.Color(0, 153, 153));
        btSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        btSal.setBorderPainted(false);
        btSal.setContentAreaFilled(false);
        btSal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSal.setFocusPainted(false);
        jPanel3.add(btSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 40, 30));

        Bot_Reporte.setBackground(new java.awt.Color(255, 255, 255));
        Bot_Reporte.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Bot_Reporte.setForeground(new java.awt.Color(18, 125, 161));
        Bot_Reporte.setText("VER TODOS");
        Bot_Reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Reporte.setFocusPainted(false);
        jPanel3.add(Bot_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 230, 40));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, -30, 80, 10));

        Bot_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_broom_25px.png"))); // NOI18N
        Bot_Limpiar.setBorderPainted(false);
        Bot_Limpiar.setContentAreaFilled(false);
        Bot_Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Limpiar.setFocusPainted(false);
        jPanel3.add(Bot_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 47, 30));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LIMPIAR");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 600, 60));

        jPanel4.setBackground(new java.awt.Color(23, 161, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORARIO MEDICO");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -1, -1, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 600, 35));

        trId.setBorder(null);
        jPanel1.add(trId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 50, 20));

        trNom.setEditable(false);
        trNom.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(trNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 150, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(18, 125, 161));
        jLabel15.setText("APELLIDO");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 30));

        trApe.setEditable(false);
        trApe.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(trApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 150, 30));

        jSeparator5.setBackground(new java.awt.Color(103, 206, 233));
        jSeparator5.setForeground(new java.awt.Color(103, 206, 233));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 20, 200));

        btAgr.setBackground(new java.awt.Color(0, 153, 153));
        btAgr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAgr.setForeground(new java.awt.Color(18, 125, 161));
        btAgr.setText("AGREGAR");
        btAgr.setBorderPainted(false);
        btAgr.setContentAreaFilled(false);
        btAgr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgr.setDefaultCapable(false);
        btAgr.setFocusPainted(false);
        jPanel1.add(btAgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 310, 110, -1));

        btMod.setBackground(new java.awt.Color(0, 153, 153));
        btMod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMod.setForeground(new java.awt.Color(18, 125, 161));
        btMod.setText("MODIFICAR");
        btMod.setBorderPainted(false);
        btMod.setContentAreaFilled(false);
        btMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMod.setDefaultCapable(false);
        btMod.setFocusPainted(false);
        jPanel1.add(btMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 110, -1));

        btEli.setBackground(new java.awt.Color(0, 153, 153));
        btEli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEli.setForeground(new java.awt.Color(18, 125, 161));
        btEli.setText("ELIMINAR");
        btEli.setBorderPainted(false);
        btEli.setContentAreaFilled(false);
        btEli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEli.setDefaultCapable(false);
        btEli.setFocusPainted(false);
        jPanel1.add(btEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 100, -1));

        jSeparator6.setBackground(new java.awt.Color(103, 206, 233));
        jSeparator6.setForeground(new java.awt.Color(103, 206, 233));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 600, 10));

        btMed.setBackground(new java.awt.Color(0, 153, 153));
        btMed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMed.setForeground(new java.awt.Color(0, 153, 153));
        btMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_veterinarian_male_42px.png"))); // NOI18N
        btMed.setBorderPainted(false);
        btMed.setContentAreaFilled(false);
        btMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMed.setDefaultCapable(false);
        btMed.setFocusPainted(false);
        jPanel1.add(btMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 50, 40));

        trCod.setBorder(null);
        jPanel1.add(trCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 20));

        trDia.setEditable(false);
        trDia.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(trDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 90, 20));

        trHI.setEditable(false);
        trHI.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(trHI, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 90, 20));

        trHF.setEditable(false);
        trHF.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(trHF, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 90, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(18, 125, 161));
        jLabel21.setText("DIA");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 40, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(18, 125, 161));
        jLabel24.setText("NOMBRE");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(97, 161, 187));
        jLabel28.setText("DIA");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 100, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(18, 125, 161));
        jLabel29.setText("HORA FIN");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 100, -1));

        trCo.setVisible(false);
        jPanel1.add(trCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 20));

        btHor.setBackground(new java.awt.Color(0, 153, 153));
        btHor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btHor.setForeground(new java.awt.Color(0, 153, 153));
        btHor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_view_schedule_40px.png"))); // NOI18N
        btHor.setBorderPainted(false);
        btHor.setContentAreaFilled(false);
        btHor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHor.setFocusPainted(false);
        jPanel1.add(btHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 50, 40));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(18, 125, 161));
        jLabel30.setText("HORA INICIO");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 100, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 80, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 65, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 90, 10));

        id_servicio.setBorder(null);
        jPanel1.add(id_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, -1));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(103, 206, 233));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVeterinaria.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HorarioEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HorarioEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HorarioEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HorarioEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HorarioEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bot_Limpiar;
    public javax.swing.JButton Bot_Reporte;
    public javax.swing.JButton btAgr;
    public javax.swing.JButton btEli;
    public javax.swing.JButton btHor;
    public javax.swing.JButton btMed;
    public javax.swing.JButton btMod;
    public javax.swing.JButton btSal;
    public javax.swing.JTextField id_servicio;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    public jtextfieldround.JTextFieldRound trApe;
    public jtextfieldround.JTextFieldRound trCo;
    public jtextfieldround.JTextFieldRound trCod;
    public jtextfieldround.JTextFieldRound trDia;
    public jtextfieldround.JTextFieldRound trHF;
    public jtextfieldround.JTextFieldRound trHI;
    public jtextfieldround.JTextFieldRound trId;
    public jtextfieldround.JTextFieldRound trNom;
    // End of variables declaration//GEN-END:variables
}
