package Vista;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class Horario extends javax.swing.JFrame {

    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Traer_Horarios = new javax.swing.JPopupMenu();
        H_Traer = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        trId = new jtextfieldround.JTextFieldRound();
        jPanel3 = new javax.swing.JPanel();
        btSal = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Bot_Limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbDia = new javax.swing.JComboBox<>();
        ftHI = new javax.swing.JFormattedTextField();
        ftHF = new javax.swing.JFormattedTextField();
        btAgr = new javax.swing.JButton();
        btMod = new javax.swing.JButton();
        btEli = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla_Horario = new rojeru_san.complementos.RSTableMetro();
        trBus = new jtextfieldround.JTextFieldRound();
        chbIn = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();

        H_Traer.setText("Devolver Datos");
        Traer_Horarios.add(H_Traer);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 252, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(23, 161, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("HORARIO");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 720, 40));

        trId.setBorder(null);
        jPanel1.add(trId, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 80, 20));

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSal.setBackground(new java.awt.Color(0, 153, 153));
        btSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSal.setForeground(new java.awt.Color(0, 153, 153));
        btSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        btSal.setToolTipText("Exit");
        btSal.setBorder(null);
        btSal.setBorderPainted(false);
        btSal.setContentAreaFilled(false);
        btSal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSal.setDefaultCapable(false);
        btSal.setFocusPainted(false);
        btSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalActionPerformed(evt);
            }
        });
        jPanel3.add(btSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SALIR");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 50, 20));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LIMPIAR");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 60, 20));

        Bot_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_broom_25px.png"))); // NOI18N
        Bot_Limpiar.setBorder(null);
        Bot_Limpiar.setBorderPainted(false);
        Bot_Limpiar.setContentAreaFilled(false);
        Bot_Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Limpiar.setFocusPainted(false);
        jPanel3.add(Bot_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, 47, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 720, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 125, 161));
        jLabel2.setText("HORA INICIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 125, 161));
        jLabel5.setText("HORA FIN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(18, 125, 161));
        jLabel11.setText("DIA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 40, -1));

        cbDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado" }));
        jPanel1.add(cbDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, -1));

        ftHI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        ftHI.setText("00:00");
        jPanel1.add(ftHI, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, -1));

        ftHF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("HH:mm"))));
        ftHF.setText("00:00");
        jPanel1.add(ftHF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 110, -1));

        btAgr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAgr.setForeground(new java.awt.Color(18, 125, 161));
        btAgr.setText("AGREGAR");
        btAgr.setBorder(null);
        btAgr.setBorderPainted(false);
        btAgr.setContentAreaFilled(false);
        btAgr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgr.setFocusPainted(false);
        jPanel1.add(btAgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, -1));

        btMod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMod.setForeground(new java.awt.Color(18, 125, 161));
        btMod.setText("MODIFICAR");
        btMod.setBorder(null);
        btMod.setBorderPainted(false);
        btMod.setContentAreaFilled(false);
        btMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMod.setFocusPainted(false);
        jPanel1.add(btMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 105, -1));

        btEli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEli.setForeground(new java.awt.Color(18, 125, 161));
        btEli.setText("ELIMINAR");
        btEli.setBorder(null);
        btEli.setBorderPainted(false);
        btEli.setContentAreaFilled(false);
        btEli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btEli.setFocusPainted(false);
        jPanel1.add(btEli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 70, 10));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 80, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 85, 10));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(103, 206, 233));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVeterinaria.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 60));

        Tabla_Horario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla_Horario.setAltoHead(25);
        Tabla_Horario.setAutoscrolls(false);
        Tabla_Horario.setColorBackgoundHead(new java.awt.Color(23, 161, 207));
        Tabla_Horario.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabla_Horario.setColorBordeHead(new java.awt.Color(255, 255, 255));
        Tabla_Horario.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabla_Horario.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Tabla_Horario.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Tabla_Horario.setColorSelBackgound(new java.awt.Color(153, 204, 255));
        Tabla_Horario.setColorSelForeground(new java.awt.Color(51, 51, 51));
        Tabla_Horario.setComponentPopupMenu(Traer_Horarios);
        Tabla_Horario.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_Horario.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_Horario.setFuenteHead(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        Tabla_Horario.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(Tabla_Horario);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 370, 210));
        jPanel1.add(trBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 210, 30));

        chbIn.setBackground(new java.awt.Color(246, 252, 254));
        chbIn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chbIn.setForeground(new java.awt.Color(18, 125, 161));
        chbIn.setText("ELIMINADOS");
        jPanel1.add(chbIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_30px_1.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bot_Limpiar;
    public javax.swing.JMenuItem H_Traer;
    public rojeru_san.complementos.RSTableMetro Tabla_Horario;
    private javax.swing.JPopupMenu Traer_Horarios;
    public javax.swing.JButton btAgr;
    public javax.swing.JButton btEli;
    public javax.swing.JButton btMod;
    public javax.swing.JButton btSal;
    public javax.swing.JComboBox<String> cbDia;
    public javax.swing.JCheckBox chbIn;
    public javax.swing.JFormattedTextField ftHF;
    public javax.swing.JFormattedTextField ftHI;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public jtextfieldround.JTextFieldRound trBus;
    public jtextfieldround.JTextFieldRound trId;
    // End of variables declaration//GEN-END:variables
}
