/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class RecuperarContraseña extends javax.swing.JFrame {

    /**
     * Creates new form RecuperarContraseña
     */
    public RecuperarContraseña() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        trId = new jtextfieldround.JTextFieldRound();
        btSal = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        trUs = new jtextfieldround.JTextFieldRound();
        trCon = new jtextfieldround.JPasswordFieldRound();
        btAgr = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 252, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(23, 161, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 30));

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(trId, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 50, 20));

        btSal.setBackground(new java.awt.Color(0, 153, 153));
        btSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSal.setForeground(new java.awt.Color(0, 153, 153));
        btSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_left_30px.png"))); // NOI18N
        btSal.setToolTipText("Salir");
        btSal.setBorder(null);
        btSal.setBorderPainted(false);
        btSal.setContentAreaFilled(false);
        btSal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSal.setFocusPainted(false);
        jPanel3.add(btSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(18, 125, 161));
        jLabel24.setText("NUEVA CONTRASEÑA");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(18, 125, 161));
        jLabel25.setText("USUARIO");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));
        jPanel1.add(trUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 220, 30));

        trCon.setDisabledTextColor(new java.awt.Color(153, 204, 255));
        trCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trConActionPerformed(evt);
            }
        });
        jPanel1.add(trCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 30));

        btAgr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAgr.setForeground(new java.awt.Color(97, 161, 187));
        btAgr.setText("CUARDAR CAMBIOS");
        btAgr.setToolTipText("");
        btAgr.setBorder(null);
        btAgr.setBorderPainted(false);
        btAgr.setContentAreaFilled(false);
        btAgr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAgr.setFocusPainted(false);
        jPanel1.add(btAgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 170, 20));

        jSeparator1.setForeground(new java.awt.Color(48, 97, 110));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 130, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperarContraseña().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btAgr;
    public javax.swing.JButton btSal;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    public jtextfieldround.JPasswordFieldRound trCon;
    public jtextfieldround.JTextFieldRound trId;
    public jtextfieldround.JTextFieldRound trUs;
    // End of variables declaration//GEN-END:variables
}
