/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author edu
 */
public class RegistroSecretaria extends javax.swing.JFrame {

    /**
     * Creates new form RegistroSecretaria
     */
    public RegistroSecretaria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Genero = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        Txt_buscar_mascota = new jtextfieldround.JTextFieldRound();
        jLabel12 = new javax.swing.JLabel();
        Bot_buscar_mascota = new javax.swing.JButton();
        ErrorFaltaTexto = new javax.swing.JLabel();
        Bot_eliminar = new javax.swing.JButton();
        Bot_registrar = new javax.swing.JButton();
        Bot_actualizar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Bot_Limpiar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Bot_Regresar = new javax.swing.JButton();
        Bot_Reporte = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        Id_Persona = new javax.swing.JTextField();
        Id_secre = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CedulaSecre = new jtextfieldround.JTextFieldRound();
        jLabel2 = new javax.swing.JLabel();
        NomPrimSecre = new jtextfieldround.JTextFieldRound();
        NomSegSecre = new jtextfieldround.JTextFieldRound();
        jLabel5 = new javax.swing.JLabel();
        ApellPriSecre = new jtextfieldround.JTextFieldRound();
        ApellSegSecre = new jtextfieldround.JTextFieldRound();
        DirecSecre = new jtextfieldround.JTextFieldRound();
        jLabel8 = new javax.swing.JLabel();
        CorreoSecre = new jtextfieldround.JTextFieldRound();
        jLabel9 = new javax.swing.JLabel();
        FechaNacSecre = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NumeroVentanilla = new jtextfieldround.JTextFieldRound();
        La_foto_paciente = new javax.swing.JLabel();
        La_foto_paciente_txt = new javax.swing.JTextField();
        ErrorCed = new javax.swing.JLabel();
        ErrorFecha = new javax.swing.JLabel();
        ErrorCorreo = new javax.swing.JLabel();
        Bot_subirFoto = new javax.swing.JButton();
        TelfSecre = new javax.swing.JFormattedTextField();
        CelularSecre = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(246, 252, 254));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(Txt_buscar_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 28, -1, 30));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(103, 206, 233));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVeterinaria.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 70));

        Bot_buscar_mascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_30px_1.png"))); // NOI18N
        Bot_buscar_mascota.setBorder(null);
        Bot_buscar_mascota.setBorderPainted(false);
        Bot_buscar_mascota.setContentAreaFilled(false);
        Bot_buscar_mascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_buscar_mascota.setFocusPainted(false);
        jPanel2.add(Bot_buscar_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 50, 40));

        ErrorFaltaTexto.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ErrorFaltaTexto.setForeground(new java.awt.Color(255, 0, 0));
        ErrorFaltaTexto.setText("* Campo Vacio");
        jPanel2.add(ErrorFaltaTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 80, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        Bot_eliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bot_eliminar.setForeground(new java.awt.Color(18, 125, 161));
        Bot_eliminar.setText("ELIMINAR");
        Bot_eliminar.setBorder(null);
        Bot_eliminar.setBorderPainted(false);
        Bot_eliminar.setContentAreaFilled(false);
        Bot_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_eliminar.setFocusPainted(false);
        Bot_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 120, 40));

        Bot_registrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bot_registrar.setForeground(new java.awt.Color(18, 125, 161));
        Bot_registrar.setText("REGISTRAR");
        Bot_registrar.setBorder(null);
        Bot_registrar.setBorderPainted(false);
        Bot_registrar.setContentAreaFilled(false);
        Bot_registrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_registrar.setFocusPainted(false);
        getContentPane().add(Bot_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 140, 40));

        Bot_actualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Bot_actualizar.setForeground(new java.awt.Color(18, 125, 161));
        Bot_actualizar.setText("ACTUALIZAR");
        Bot_actualizar.setBorder(null);
        Bot_actualizar.setBorderPainted(false);
        Bot_actualizar.setContentAreaFilled(false);
        Bot_actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_actualizar.setFocusPainted(false);
        Bot_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Bot_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 140, 40));

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO SECRETARIA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(332, 332, 332))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1000, 40));

        jPanel4.setBackground(new java.awt.Color(23, 161, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("LIMPIAR");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 30));

        Bot_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_broom_25px.png"))); // NOI18N
        Bot_Limpiar.setBorder(null);
        Bot_Limpiar.setBorderPainted(false);
        Bot_Limpiar.setContentAreaFilled(false);
        Bot_Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Limpiar.setFocusPainted(false);
        jPanel4.add(Bot_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 70, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("SALIR");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 50, 30));

        Bot_Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        Bot_Regresar.setBorder(null);
        Bot_Regresar.setBorderPainted(false);
        Bot_Regresar.setContentAreaFilled(false);
        Bot_Regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Regresar.setFocusPainted(false);
        jPanel4.add(Bot_Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 50, 30));

        Bot_Reporte.setBackground(new java.awt.Color(255, 255, 255));
        Bot_Reporte.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Bot_Reporte.setForeground(new java.awt.Color(18, 125, 161));
        Bot_Reporte.setText("VER TODOS");
        Bot_Reporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_Reporte.setFocusPainted(false);
        jPanel4.add(Bot_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 230, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 545, 1000, 60));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 100, 30));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 100, 30));
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 100, 30));

        Id_Persona.setBorder(null);
        getContentPane().add(Id_Persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 30, 30));

        Id_secre.setBorder(null);
        getContentPane().add(Id_secre, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 30, 30));

        jPanel5.setBackground(new java.awt.Color(246, 252, 254));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(18, 125, 161));
        jLabel11.setText("CEDULA");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 20));

        CedulaSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaSecreActionPerformed(evt);
            }
        });
        jPanel5.add(CedulaSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 260, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 125, 161));
        jLabel2.setText("NOMBRES");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));

        NomPrimSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomPrimSecreActionPerformed(evt);
            }
        });
        jPanel5.add(NomPrimSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 130, -1));

        NomSegSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomSegSecreActionPerformed(evt);
            }
        });
        jPanel5.add(NomSegSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(18, 125, 161));
        jLabel5.setText("APELLIDOS");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, 20));

        ApellPriSecre.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        ApellPriSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellPriSecreActionPerformed(evt);
            }
        });
        jPanel5.add(ApellPriSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 130, 30));

        ApellSegSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellSegSecreActionPerformed(evt);
            }
        });
        jPanel5.add(ApellSegSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 130, 30));

        DirecSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirecSecreActionPerformed(evt);
            }
        });
        jPanel5.add(DirecSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 260, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(18, 125, 161));
        jLabel8.setText("DIRECCION");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        CorreoSecre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoSecreActionPerformed(evt);
            }
        });
        jPanel5.add(CorreoSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 260, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(18, 125, 161));
        jLabel9.setText("CORREO");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        FechaNacSecre.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.add(FechaNacSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 260, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(18, 125, 161));
        jLabel4.setText("FECHA NACIMIENTO");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, 20));

        Masculino.setBackground(new java.awt.Color(246, 252, 254));
        Genero.add(Masculino);
        Masculino.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Masculino.setForeground(new java.awt.Color(18, 125, 161));
        Masculino.setText("Masculino");
        Masculino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });
        jPanel5.add(Masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, -1, -1));

        Femenino.setBackground(new java.awt.Color(246, 252, 254));
        Genero.add(Femenino);
        Femenino.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        Femenino.setForeground(new java.awt.Color(18, 125, 161));
        Femenino.setText("Femenino");
        Femenino.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });
        jPanel5.add(Femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(18, 125, 161));
        jLabel3.setText("GENERO");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(18, 125, 161));
        jLabel10.setText("TELEFONO");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(18, 125, 161));
        jLabel7.setText("CELULAR");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(18, 125, 161));
        jLabel6.setText("NUMERO VENTANILLA");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));
        jPanel5.add(NumeroVentanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 380, 70, -1));

        La_foto_paciente.setForeground(new java.awt.Color(18, 125, 161));
        La_foto_paciente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 161, 187), 2));
        jPanel5.add(La_foto_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 100));
        jPanel5.add(La_foto_paciente_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 420, 80, 10));

        ErrorCed.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ErrorCed.setForeground(new java.awt.Color(255, 0, 0));
        ErrorCed.setText("* Verifique su cédula");
        jPanel5.add(ErrorCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 140, 20));

        ErrorFecha.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ErrorFecha.setForeground(new java.awt.Color(255, 0, 0));
        ErrorFecha.setText("* Verifique su Fecha de nacimineto");
        jPanel5.add(ErrorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 160, 20));

        ErrorCorreo.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        ErrorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        ErrorCorreo.setText("* Verifique su correo");
        jPanel5.add(ErrorCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 160, 20));

        Bot_subirFoto.setBackground(new java.awt.Color(23, 161, 207));
        Bot_subirFoto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Bot_subirFoto.setForeground(new java.awt.Color(255, 255, 255));
        Bot_subirFoto.setText("SUBIR FOTO");
        Bot_subirFoto.setBorderPainted(false);
        Bot_subirFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_subirFoto.setFocusPainted(false);
        jPanel5.add(Bot_subirFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));

        try {
            TelfSecre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(07)-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TelfSecre.setToolTipText("Ejemplo de nº de telefono: (07)234-2893");
        jPanel5.add(TelfSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 220, 30));

        try {
            CelularSecre.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(593)-###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        CelularSecre.setToolTipText("Ejemplo de nº de celular: (593)098-406-6690");
        jPanel5.add(CelularSecre, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 220, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bot_eliminarActionPerformed

    private void Bot_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot_actualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bot_actualizarActionPerformed

    private void NomSegSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomSegSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomSegSecreActionPerformed

    private void NomPrimSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomPrimSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomPrimSecreActionPerformed

    private void ApellPriSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellPriSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellPriSecreActionPerformed

    private void ApellSegSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellSegSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellSegSecreActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinoActionPerformed

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemeninoActionPerformed

    private void CorreoSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoSecreActionPerformed

    private void DirecSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirecSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DirecSecreActionPerformed

    private void CedulaSecreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaSecreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaSecreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroSecretaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroSecretaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public jtextfieldround.JTextFieldRound ApellPriSecre;
    public jtextfieldround.JTextFieldRound ApellSegSecre;
    public javax.swing.JButton Bot_Limpiar;
    public javax.swing.JButton Bot_Regresar;
    public javax.swing.JButton Bot_Reporte;
    public javax.swing.JButton Bot_actualizar;
    public javax.swing.JButton Bot_buscar_mascota;
    public javax.swing.JButton Bot_eliminar;
    public javax.swing.JButton Bot_registrar;
    public javax.swing.JButton Bot_subirFoto;
    public jtextfieldround.JTextFieldRound CedulaSecre;
    public javax.swing.JFormattedTextField CelularSecre;
    public jtextfieldround.JTextFieldRound CorreoSecre;
    public jtextfieldround.JTextFieldRound DirecSecre;
    public javax.swing.JLabel ErrorCed;
    public javax.swing.JLabel ErrorCorreo;
    public javax.swing.JLabel ErrorFaltaTexto;
    public javax.swing.JLabel ErrorFecha;
    public com.toedter.calendar.JDateChooser FechaNacSecre;
    public javax.swing.JRadioButton Femenino;
    public javax.swing.ButtonGroup Genero;
    public javax.swing.JTextField Id_Persona;
    public javax.swing.JTextField Id_secre;
    public javax.swing.JLabel La_foto_paciente;
    public javax.swing.JTextField La_foto_paciente_txt;
    public javax.swing.JRadioButton Masculino;
    public jtextfieldround.JTextFieldRound NomPrimSecre;
    public jtextfieldround.JTextFieldRound NomSegSecre;
    public jtextfieldround.JTextFieldRound NumeroVentanilla;
    public javax.swing.JFormattedTextField TelfSecre;
    public jtextfieldround.JTextFieldRound Txt_buscar_mascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
