/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class RegistrosEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form RegistrosEmpleados
     */
    public RegistrosEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        trId = new jtextfieldround.JTextFieldRound();
        jLabel4 = new javax.swing.JLabel();
        btSal = new javax.swing.JButton();
        trBus = new jtextfieldround.JTextFieldRound();
        btBu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_REg_Empleado = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(23, 161, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE VETERINARIOS");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 80));

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(trId, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 50, 20));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        btSal.setBackground(new java.awt.Color(0, 153, 153));
        btSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSal.setForeground(new java.awt.Color(0, 153, 153));
        btSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        btSal.setBorder(null);
        btSal.setBorderPainted(false);
        btSal.setContentAreaFilled(false);
        btSal.setFocusPainted(false);
        jPanel3.add(btSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 40, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 690, 50));
        jPanel1.add(trBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 210, 30));

        btBu.setBackground(new java.awt.Color(0, 153, 153));
        btBu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btBu.setForeground(new java.awt.Color(0, 153, 153));
        btBu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_30px_1.png"))); // NOI18N
        btBu.setBorder(null);
        btBu.setBorderPainted(false);
        btBu.setContentAreaFilled(false);
        btBu.setFocusPainted(false);
        jPanel1.add(btBu, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 40, 30));

        Tabla_REg_Empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla_REg_Empleado.setAltoHead(25);
        Tabla_REg_Empleado.setAutoscrolls(false);
        Tabla_REg_Empleado.setColorBackgoundHead(new java.awt.Color(23, 161, 207));
        Tabla_REg_Empleado.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabla_REg_Empleado.setColorBordeHead(new java.awt.Color(255, 255, 255));
        Tabla_REg_Empleado.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabla_REg_Empleado.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Tabla_REg_Empleado.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Tabla_REg_Empleado.setColorSelBackgound(new java.awt.Color(153, 204, 255));
        Tabla_REg_Empleado.setColorSelForeground(new java.awt.Color(51, 51, 51));
        Tabla_REg_Empleado.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_REg_Empleado.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_REg_Empleado.setFuenteHead(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        Tabla_REg_Empleado.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(Tabla_REg_Empleado);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 660, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrosEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrosEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public rojeru_san.complementos.RSTableMetro Tabla_REg_Empleado;
    public javax.swing.JButton btBu;
    public javax.swing.JButton btSal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    public jtextfieldround.JTextFieldRound trBus;
    public jtextfieldround.JTextFieldRound trId;
    // End of variables declaration//GEN-END:variables
}
