/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author USUARIO
 */
public class Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        btEli = new javax.swing.JMenuItem();
        Restaurar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btSal = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Bot_limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        trCo = new jtextfieldround.JTextFieldRound();
        jLabel11 = new javax.swing.JLabel();
        cbEm = new javax.swing.JComboBox<>();
        btAgr = new javax.swing.JButton();
        btMod = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        trUs = new jtextfieldround.JTextFieldRound();
        trBuscar = new jtextfieldround.JTextFieldRound();
        jLabel14 = new javax.swing.JLabel();
        btSec = new javax.swing.JButton();
        btMed = new javax.swing.JButton();
        trCon = new jtextfieldround.JPasswordFieldRound();
        trId = new jtextfieldround.JTextFieldRound();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        chbIn = new javax.swing.JCheckBox();
        Bot_buscar_paciente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla_Usuario = new rojeru_san.complementos.RSTableMetro();

        btEli.setText("Inhabilitar ");
        jPopupMenu1.add(btEli);

        Restaurar.setText("Restaurar");
        jPopupMenu1.add(Restaurar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(246, 252, 254));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(23, 161, 207));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("USUARIOS");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 910, 50));

        jPanel3.setBackground(new java.awt.Color(23, 161, 207));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SALIR");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        btSal.setBackground(new java.awt.Color(0, 153, 153));
        btSal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSal.setForeground(new java.awt.Color(0, 153, 153));
        btSal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_exit_25px.png"))); // NOI18N
        btSal.setBorder(null);
        btSal.setContentAreaFilled(false);
        btSal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSal.setFocusPainted(false);
        jPanel3.add(btSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 40, 30));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LIMPIAR");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        Bot_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_broom_25px.png"))); // NOI18N
        Bot_limpiar.setBorderPainted(false);
        Bot_limpiar.setContentAreaFilled(false);
        Bot_limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_limpiar.setFocusPainted(false);
        jPanel3.add(Bot_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 64, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 910, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(18, 125, 161));
        jLabel2.setText("EMPLEADOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));
        jPanel1.add(trCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 130, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(18, 125, 161));
        jLabel11.setText("USUARIO :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 80, -1));

        cbEm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Secretaria", "Veterinario" }));
        jPanel1.add(cbEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, -1));

        btAgr.setBackground(new java.awt.Color(0, 153, 153));
        btAgr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btAgr.setForeground(new java.awt.Color(18, 125, 161));
        btAgr.setText("REGISTRAR");
        btAgr.setBorderPainted(false);
        btAgr.setContentAreaFilled(false);
        btAgr.setDefaultCapable(false);
        btAgr.setFocusPainted(false);
        jPanel1.add(btAgr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 120, -1));

        btMod.setBackground(new java.awt.Color(0, 153, 153));
        btMod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMod.setForeground(new java.awt.Color(18, 125, 161));
        btMod.setText("MODIFICAR");
        btMod.setBorderPainted(false);
        btMod.setContentAreaFilled(false);
        btMod.setDefaultCapable(false);
        btMod.setFocusPainted(false);
        jPanel1.add(btMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(18, 125, 161));
        jLabel13.setText("CODIGO :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 80, -1));
        jPanel1.add(trUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 130, 20));
        jPanel1.add(trBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 200, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(18, 125, 161));
        jLabel14.setText("CONTRASEÑA :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 110, -1));

        btSec.setBackground(new java.awt.Color(0, 153, 153));
        btSec.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSec.setForeground(new java.awt.Color(0, 153, 153));
        btSec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_technical_support_40px.png"))); // NOI18N
        btSec.setBorder(null);
        btSec.setContentAreaFilled(false);
        btSec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSec.setEnabled(false);
        btSec.setFocusPainted(false);
        jPanel1.add(btSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 40, -1));

        btMed.setBackground(new java.awt.Color(0, 153, 153));
        btMed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btMed.setForeground(new java.awt.Color(0, 153, 153));
        btMed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_veterinarian_male_42px.png"))); // NOI18N
        btMed.setBorder(null);
        btMed.setContentAreaFilled(false);
        btMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btMed.setEnabled(false);
        btMed.setFocusPainted(false);
        jPanel1.add(btMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 40, 40));

        trCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trConActionPerformed(evt);
            }
        });
        jPanel1.add(trCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 130, 20));

        trId.setBorder(null);
        trId.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        trId.setEnabled(false);
        jPanel1.add(trId, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 50, 30));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 90, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 80, 10));

        chbIn.setBackground(new java.awt.Color(246, 252, 254));
        chbIn.setForeground(new java.awt.Color(18, 125, 161));
        chbIn.setText("Inactivos");
        jPanel1.add(chbIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        Bot_buscar_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/icons8_search_30px_1.png"))); // NOI18N
        Bot_buscar_paciente.setBorder(null);
        Bot_buscar_paciente.setBorderPainted(false);
        Bot_buscar_paciente.setContentAreaFilled(false);
        Bot_buscar_paciente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bot_buscar_paciente.setFocusPainted(false);
        jPanel1.add(Bot_buscar_paciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 40, 30));

        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(103, 206, 233));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVeterinaria.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 70));

        Tabla_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla_Usuario.setAltoHead(25);
        Tabla_Usuario.setAutoscrolls(false);
        Tabla_Usuario.setColorBackgoundHead(new java.awt.Color(23, 161, 207));
        Tabla_Usuario.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        Tabla_Usuario.setColorBordeHead(new java.awt.Color(255, 255, 255));
        Tabla_Usuario.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        Tabla_Usuario.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Tabla_Usuario.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Tabla_Usuario.setColorSelBackgound(new java.awt.Color(153, 204, 255));
        Tabla_Usuario.setColorSelForeground(new java.awt.Color(51, 51, 51));
        Tabla_Usuario.setComponentPopupMenu(jPopupMenu1);
        Tabla_Usuario.setFuenteFilas(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_Usuario.setFuenteFilasSelect(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Tabla_Usuario.setFuenteHead(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        Tabla_Usuario.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(Tabla_Usuario);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 590, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trConActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Bot_buscar_paciente;
    public javax.swing.JButton Bot_limpiar;
    public javax.swing.JMenuItem Restaurar;
    public rojeru_san.complementos.RSTableMetro Tabla_Usuario;
    public javax.swing.JButton btAgr;
    public javax.swing.JMenuItem btEli;
    public javax.swing.JButton btMed;
    public javax.swing.JButton btMod;
    public javax.swing.JButton btSal;
    public javax.swing.JButton btSec;
    public javax.swing.JComboBox<String> cbEm;
    public javax.swing.JCheckBox chbIn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public jtextfieldround.JTextFieldRound trBuscar;
    public jtextfieldround.JTextFieldRound trCo;
    public jtextfieldround.JPasswordFieldRound trCon;
    public jtextfieldround.JTextFieldRound trId;
    public jtextfieldround.JTextFieldRound trUs;
    // End of variables declaration//GEN-END:variables
}
